name: release
on:
  push:
    branches:
      - 'master'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Node & NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node_modules
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
